[tool.briefcase]
project_name = "Dynamo Gas"
bundle = "com.dynamogroup"
version = "0.0.1"
url = "https://dynamogroup.com/dynamogas"
license = "BSD license"
author = 'Lekia Prosper Kiisi'
author_email = "lekiaprosper@gmail.com"

[tool.briefcase.app.dynamogas]
formal_name = "Dynamo Gas"
description = "Dynamo Gas is a native application for making transaction entries, and data analysis for gas sales companies."
icon = "src/dynamogas/resources/dynamogas"
sources = ['src/dynamogas']
requires = [
    'pandas',
    'tabulate',
]


[tool.briefcase.app.dynamogas.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.dynamogas.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.dynamogas.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.dynamogas.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.dynamogas.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.dynamogas.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.dynamogas.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
