[tool.briefcase]
project_name = "Dynamos gas"
bundle = "com.dynamogroup"
version = "0.0.1"
url = "https://dynamogroup.com/dynamosgas"
license = "MIT license"
author = 'PilotX Lab(Lekia Prosper)'
author_email = "lekiaprosper@gmail.com"

[tool.briefcase.app.dynamosgas]
formal_name = "Dynamos gas"
description = "Dynamo gas is a native application for making transaction entries, and data analysis for gas sales companies"
icon = "src/dynamosgas/resources/dynamosgas"
sources = ['src/dynamosgas']
requires = [
    'pandas',
    'tabulate',
]


[tool.briefcase.app.dynamosgas.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.dynamosgas.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.dynamosgas.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.dynamosgas.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.dynamosgas.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.dynamosgas.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.dynamosgas.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
